# Voice IVR System Docker Compose Configuration

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5678:5678"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - PORT=5678
      - WEBHOOK_AUTH_TOKEN=${WEBHOOK_AUTH_TOKEN}
      - EIGHT_X_EIGHT_API_KEY=${EIGHT_X_EIGHT_API_KEY}
      - EIGHT_X_EIGHT_SUBACCOUNT_ID=${EIGHT_X_EIGHT_SUBACCOUNT_ID}
      - OUTBOUND_PHONE_NUMBER=${OUTBOUND_PHONE_NUMBER}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5678/health"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
    restart: unless-stopped
  # Custom ngrok service
  ngrok-custom:
    build:
      context: .
      dockerfile: Dockerfile.ngrok
    ports:
      - "4040:4040"
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
      - WEBHOOK_BASE_URL=${WEBHOOK_BASE_URL}
      - TARGET_HOST=backend
      - TARGET_PORT=5678
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped

networks:
  default:
    name: voice_ivr_static_network
